recipes = [
    {"name": "Leinölfrühstücksquark mit Beeren", "calories": 520, "protein": 32, "fat": 24, "carbs": 40, "fiber": 10, "type": "Frühstück"},
    {"name": "Coffee-Overnight-Oates mit Papaya", "calories": 310, "protein": 10, "fat": 11, "carbs": 35, "fiber": 12, "type": "Frühstück"},
    {"name": "Süßlupinen-Porridge mit Birnen", "calories": 575, "protein": 24, "fat": 19, "carbs": 67, "fiber": 18, "type": "Frühstück"},
    {"name": "Grüne Shakshuka mit Spinat", "calories": 520, "protein": 33, "fat": 33, "carbs": 19, "fiber": 9, "type": "Frühstück"},
    {"name": "Pilz-Lauch-Omelette mit Feta", "calories": 500, "protein": 27, "fat": 40, "carbs": 6, "fiber": 3, "type": "Frühstück"},
    {"name": "Gersten-Fenchel-Salat mit Halloumi", "calories": 650, "protein": 27, "fat": 36, "carbs": 49, "fiber": 11, "type": "Sattmacher"},
    {"name": "Reis-Linsen-Salat mit Mangold", "calories": 540, "protein": 16, "fat": 25, "carbs": 58, "fiber": 8, "type": "Sattmacher"},
    {"name": "Brokkoli-Pasta mit Cashewsauce", "calories": 699, "protein": 28, "fat": 33, "carbs": 62, "fiber": 19, "type": "Sattmacher"},
    {"name": "Asiatischer Nudel-Gemüse-Wok", "calories": 500, "protein": 23, "fat": 19, "carbs": 52, "fiber": 14, "type": "Sattmacher"},
    {"name": "Kürbis-Kokos-Curry mit Tofu", "calories": 500, "protein": 19, "fat": 33, "carbs": 32, "fiber": 8, "type": "Sattmacher"},
    {"name": "Gegrillter Lachs mit Peperonata", "calories": 640, "protein": 40, "fat": 35, "carbs": 36, "fiber": 10, "type": "Sattmacher"},
    {"name": "Grüner Gemüse-Wok mit Hähnchen", "calories": 550, "protein": 41, "fat": 26, "carbs": 29, "fiber": 14, "type": "Sattmacher"},
    {"name": "Sesamschnitzel mit Asia-Gemüse", "calories": 670, "protein": 56, "fat": 25, "carbs": 52, "fiber": 8, "type": "Sattmacher"},
    {"name": "Avocadosalat mit Kichererbsen", "calories": 460, "protein": 12, "fat": 37, "carbs": 14, "fiber": 7, "type": "Low-Carb"},
    {"name": "Ratatouille-Halloumi-Eintopf", "calories": 540, "protein": 25, "fat": 40, "carbs": 16, "fiber": 9, "type": "Low-Carb"},
    {"name": "Selleriesuppe mit Nuss-Gremolata", "calories": 320, "protein": 6, "fat": 27, "carbs": 14, "fiber": 4, "type": "Low-Carb"},
    {"name": "Rote Linsen-Kokos-Suppe", "calories": 550, "protein": 12, "fat": 42, "carbs": 29, "fiber": 11, "type": "Low-Carb"},
    {"name": "Aprikosensalat mit Garnelen", "calories": 460, "protein": 28, "fat": 31, "carbs": 13, "fiber": 6, "type": "Low-Carb"},
    {"name": "Gemüse-Antipasti mit Salbeipute", "calories": 400, "protein": 36, "fat": 22, "carbs": 11, "fiber": 6, "type": "Low-Carb"},
    {"name": "Thunfisch Salat", "calories": 139, "protein": 32, "fat": 1, "carbs": 1, "fiber": 0, "type": None},
    {"name": "Quark Beeren Milchshake", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "fiber": 0, "type": None},
]
